# Generated by Django 5.2.17 on 2026-09-01 20:40

import django.core.validators
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('cbs_email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('country_of_origin', models.CharField(blank=True, max_length=120)),
                ('previous_employment', models.CharField(blank=True, max_length=240)),
                ('undergraduate_institution', models.CharField(blank=True, max_length=240)),
                ('desired_industry', models.CharField(blank=True, max_length=200)),
                ('hobbies', models.TextField(blank=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('linkedin_url', models.URLField(blank=True, validators=[profiles.validators.validate_linkedin_url])),
                ('consent_confirmed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
